### ISSUE TITLE
Eliminate XML button

### ISSUE THREAD

**Issue by hackman104** [BirkbeckCTP/pandoc_plugin#2]
XML button produces same thing as HTML - either eliminate or explore JATS.

**Comment by mdlincoln** [comment]
You can't really export JATS via pandoc, since all that pandoc does with the JATS template is set the article metadata. All body formatting is ignored.

**Comment by ajrbyers** [comment]
Yes I think this was one too far. A JATS stub may be useful but not via Pandoc anyway.

**Comment by mdlincoln** [comment]
I have a PR for this I can merge after closing #5
