### ISSUE TITLE
graceful error message if pandoc fails

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/pandoc_plugin#3]
If pandoc chokes on the file it tries to convert, it should display a meaningful message in the management interface. Right now, it always assumes that pandoc will work, and so sends the user to a non-existent URL if no file was successfully converted.

**Comment by mdlincoln** [comment]
@ajrbyers how does Janeway like to display errors that need to be seen by humans in the management interface?

**Comment by ajrbyers** [comment]
We use the Messages framework:

https://docs.djangoproject.com/en/1.11/ref/contrib/messages/

These errors then appear as Toasts with different colours dependent on the message level.

**Comment by mdlincoln** [comment]
This was closed by #8
